### ISSUE TITLE
Undefined method 'verifications_admin' for User factory

### ISSUE THREAD

**Issue by zuzust** [GuanyemBarcelona/participa#30]
@andreslucena, execution of `rake db:seed` task fails and outputs:

```
NoMethodError: undefined method `verifications_admin=' for #<User:0x007fe21b033ae0>
```

Indeed, no `verifications_admin` setter defined in User factory.

**Comment by andreslucena** [comment]
It seems like it's an error with the flag_shih_tzu gem on the User model. I'll check it and let you know.
